class WriterAgent:
    def __init__(self, output_file='static/audience_report.txt'):
        self.output_file = output_file

    def write_report(self, analytics_data):
        if "error" in analytics_data:
            return f"Could not generate report: {analytics_data['error']}"

        report = f"""
==================================================
🚀 AI WORKSHOP - AUDIENCE INTELLIGENCE REPORT
==================================================

📊 TOTAL PARTICIPANTS: {analytics_data['total_participants']}

--------------------------------------------------
1️⃣ EXPERIENCE LEVELS
--------------------------------------------------
"""
        for level, count in analytics_data['experience_breakdown'].items():
            report += f"- {level}: {count}\n"

        report += """
--------------------------------------------------
2️⃣ PROGRAMMING CONFIDENCE
--------------------------------------------------
"""
        for level, count in analytics_data['confidence_breakdown'].items():
            report += f"- {level}: {count}\n"

        report += """
--------------------------------------------------
3️⃣ TOP DOMAINS
--------------------------------------------------
"""
        for domain, count in analytics_data['top_domains'].items():
            report += f"- {domain}: {count}\n"

        report += """
--------------------------------------------------
4️⃣ INTEREST CLUSTERS (What they want to build)
--------------------------------------------------
"""
        for group, count in analytics_data['interest_clusters'].items():
            report += f"- {group}: {count}\n"

        report += "\n==================================================\n"
        report += "Report generated by Agent 2 (Writer Agent)"

        # Save to file
        with open(self.output_file, 'w') as f:
            f.write(report)

        return report
